### ISSUE TITLE
libstdc++ out of date: version CXXABI_1.3.9' not found, versionGLIBCXX_3.4.21' not found

### ISSUE THREAD

**Issue by Fergus-Boyd** [mamonu/bumblebee#38]
pyenchant relies on a version > libstdc++.so.6.0.19.

The top response to this stackoverflow question solved the issue for me.

https://stackoverflow.com/questions/49797965/updating-libstdc-so-6-to-glibcxx-3-4-21-and-cxxabi-1-3-9-after-updating-to-gcc

**Comment by mamonu** [comment]
That's on Ubuntu 14.04 and and your version of Python is Python > 3.6 right?

thanks for the suggestion and help.
